{% set name = "moderngl" %}
{% set version = "5.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/moderngl/archive/{{ version }}.tar.gz
  sha256: 7d13354ef4b450fb4f2546eb32f8a3670f05df117467b5df94eaf9296c098832

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}              # [linux]
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}      # [linux]

  host:
    - python
    - pip
    - numpy
    - setuptools

  run:
    - python
    - glcontext

test:
  imports:
    - moderngl
    - moderngl.mgl

about:
  home: https://github.com/moderngl/moderngl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern OpenGL binding for python

extra:
  recipe-maintainers:
    - pavelzw
    - cprogrammer1994
    - patricksnape
