{% set name = "moderngl" %}
{% set version = "5.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moderngl/moderngl/archive/{{ version }}.tar.gz
  sha256: 3648b961cf512decf09fbfebe745352970e31e95d93e94dd2bc7106a2446e338

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]

  host:
    - python
    - pip
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - glcontext

test:
  imports:
    - moderngl
    - moderngl.mgl

about:
  home: https://github.com/moderngl/moderngl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern OpenGL binding for python

extra:
  recipe-maintainers:
    - cprogrammer1994
    - patricksnape
